openapi: 3.0.0
info:
  version: 1.0.5
  title: Site Preferences
components:
  securitySchemes:
    ShopperToken:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://[REPLACE_WITH_SHORT_CODE].commercecloud.salesforce.com/shopper/auth/v1/organizations/[REPLACE_WITH_ORG_ID]/oauth2/authorize
          tokenUrl: https://[REPLACE_WITH_SHORT_CODE].commercecloud.salesforce.com/shopper/auth/v1/organizations/[REPLACE_WITH_ORG_ID]/oauth2/token
          scopes:
            c_apiScope_r: Read loyalty information of a customer
        clientCredentials:
          tokenUrl: https://[REPLACE_WITH_SHORT_CODE].commercecloud.salesforce.com/shopper/auth/v1/organizations/[REPLACE_WITH_ORG_ID]/oauth2/token
          scopes:
            c_apiScope_r: Read loyalty information of a customer
paths:
  /get-preferences:
    get:
      summary: "Get Specific Site Preferences"
      operationId: getSitePreferences
      parameters:
        - in: query
          name: siteId
          required: true
          schema:
            type: string
            minLength: 1
            description: The identifier of the site
        - in: query
          name: locale
          required: true
          schema:
            type: string
            minLength: 1
            description: The identifier of the site locale
        - in: query
          name: c_segment
          required: false
          schema:
            type: string
            minLength: 1
            description: The identifier of the site custom preference group
      responses:
        200:
          description: OK
security:
  - ShopperToken: ['c_apiScope_r']
